batch:
  scheduler:
    test: 0/5 * * * * ?
    employee: 0/5 * * * *
  
spring:
  batch:
    job:
      enabled: false
  datasource:
    initialize: true
    schema: classpath:schema.sql
    url: jdbc:h2:file:./DB
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
